### ISSUE TITLE
Terraform Escalation Path - round robin: nil pointer dereference

### ISSUE THREAD

**Issue by whites11** [incident-io/terraform-provider-incident#99]
[Here](https://registry.terraform.io/providers/incident-io/incident/latest/docs/resources/escalation_path#rotate_after_seconds) you mention that `rotate_after_seconds` field is optional, but [here](https://github.com/incident-io/terraform-provider-incident/blob/master/internal/provider/incident_escalation_path_resource.go#L411C43-L411C68) you dereference the pointer without nil checking, making the provider to panic if `rotate_after_seconds` field is not set.

**Comment by whites11** [comment]
even worse, once you end up in this situation, `terraform plan` will begin panicking and there is no way to recover it without deleting the round robin "step" from the "escalation".

**Comment by rorydbain** [comment]
Hey @whites11, apologies it took us so long to get to this one. I've pushed a fix in #102. 

Whilst investigating it I've spotted that much of our documentation around these fields isn't being pulled through in the Terraform provider, which certainly doesn't help things. I've opened a ticket on our side to sort that out too.
